#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run start-checks
node helpers/check-no-sub-node-modules.js
node helpers/eslint.js
npx lint-staged -rq

if [[ `git diff @ --name-only | grep -E "^packages/common/"` != "" ]]; then
  npm run api:ts:noWatch
  npm run website:ts:noWatch

  exit 0
fi

if [[ `git diff @ --name-only | grep -E "^packages/api/"` != "" ]]; then
  npm run api:ts:noWatch
fi
if [[ `git diff @ --name-only | grep -E "^packages/website/"` != "" ]]; then
  npm run website:ts:noWatch
fi
